dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0  # Motor principal (android/iOS)
  sqflite_common_ffi: ^2.3.0 # soporte nativo para desktop (linux/windows)
  path_provider: ^2.1.1 #para encontrar la ruta de documentos del SO
  path: ^1.8.3 #utilidades de rutas de archivos
